name: pure_result
description: A sealed Result<T, E> package for Dart and Flutter to model success and failure explicitly in app, package, and async domain error handling.
version: 0.1.3
homepage: https://github.com/kanata996/pure_result
repository: https://github.com/kanata996/pure_result
issue_tracker: https://github.com/kanata996/pure_result/issues
topics:
  - result
  - functional
  - error-handling

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  mutation_test: ^1.8.0
  test: ^1.25.15
